version: "3.9"

services:
  robot:
    container_name: socket-server
    build:
      dockerfile: Dockerfile
      context: .
    image: lwaero/socket-server
    restart: always
    ports:
    - 8080:8080
    volumes:
    - ./src:/app/src
    - node_modules_ws:/app/src/node_modules
    env_file:
      - .env

volumes:
  node_modules_ws: